name = "missmatch"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "missmatch-db"
database_id = "local" # ローカル開発用ダミー、本番デプロイ時に変更

[[kv_namespaces]]
binding = "CACHE"
id = "local" # ローカル開発用ダミー、本番デプロイ時に変更
